namespace util;
import "std/core.sunder";

struct allocation_failure_allocator {
    func allocate(self: *allocation_failure_allocator, align: usize, size: usize) std::result[[*byte, []byte]] {
        return std::result[[*byte, []byte]]::init_error(std::allocator::ERROR_ALLOCATION_FAILURE);
    }

    # Reallocation will panic since a call to allocate should never have
    # succeeded, so any provided pointer is invalid.
    func reallocate(self: *allocation_failure_allocator, ptr: *byte, align: usize, old_size: usize, new_size: usize) std::result[[*byte, []byte]] {
        std::panic("attempted allocation_failure_allocator reallocation");
        return std::zeroed[[std::result[[*byte, []byte]]]](); # unreachable
    }

    # Deallocation will panic since a call to allocate should never have
    # succeeded, so any provided pointer is invalid.
    func deallocate(self: *allocation_failure_allocator, ptr: *byte, align: usize, size: usize) void {
        std::panic("attempted allocation_failure_allocator deallocation");
    }

    func the() *allocation_failure_allocator {
        const the = (:allocation_failure_allocator){};
        return &the;
    }
}
